name: Test Suite

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --no-fund --no-audit --legacy-peer-deps
      
    - name: Create jest.setup.js if missing
      run: |
        if [ ! -f jest.setup.js ]; then
          echo "require('@testing-library/jest-dom');" > jest.setup.js
        fi
    
    - name: Install Jest globally
      run: npm install -g jest
    
    - name: Run tests
      run: jest --passWithNoTests
      
    - name: Run tests with coverage
      run: jest --coverage --passWithNoTests
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/
        fail_ci_if_error: false
